[package]
name = "gmon"
version = "0.1.0"
authors = ["Justin Goncalves <justingoncalves023@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
